#yaml? ??? ? :
#spring.application.name=ChatWebApplication
# intellij?? ??? ????? ??? static ??? ? ??? ??? ????? ??
spring:
    devtools:
        livereload:
            enabled: true
    restart:
        enabled: false
    freemarker:
        cache: false
    application:
        name: ChatWebApplication
